//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_USERS
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
